name: "Deploy Full Stack"

# This section tells GitHub WHEN to run
on:
  push:
    branches:
      - main
    paths:
      - 'app-code/**'
      - '.github/workflows/deploy-app.yml' # Optional: runs if you edit the workflow itself

jobs:
  build-and-deploy:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- BACKEND SECTION ---
      - name: Build and Push Backend
        env:
          ECR_URL: 747554529915.dkr.ecr.us-east-1.amazonaws.com/test-infra/backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URL:$IMAGE_TAG ./app-code/backend
          docker push $ECR_URL:$IMAGE_TAG
          docker tag $ECR_URL:$IMAGE_TAG $ECR_URL:latest
          docker push $ECR_URL:latest

      # --- FRONTEND SECTION ---
      - name: Build and Push Frontend
        env:
          ECR_URL: 747554529915.dkr.ecr.us-east-1.amazonaws.com/test-infra/frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URL:$IMAGE_TAG ./app-code/frontend
          docker push $ECR_URL:$IMAGE_TAG
          docker tag $ECR_URL:$IMAGE_TAG $ECR_URL:latest
          docker push $ECR_URL:latest

      # --- UPDATE ECS ---
      - name: Deploy to Amazon ECS
        run: |
          # This tells ECS to pull the latest image we just pushed
          aws ecs update-service --cluster test-app-cluster --service backend --force-new-deployment
          aws ecs update-service --cluster test-app-cluster --service frontend --force-new-deployment